2022-09-09 19:11:48.760827 | Traceback (most recent call last):
  File "C:/ALEVEL/PYONLINE2/lesson4/lesson4_practice_review.py", line 35, in <module>
    main()
  File "C:/ALEVEL/PYONLINE2/lesson4/lesson4_practice_review.py", line 30, in main
    emp3 = Employee("John", 14, "johnDoe@gmail.com")
  File "C:/ALEVEL/PYONLINE2/lesson4/lesson4_practice_review.py", line 12, in __init__
    self.validate_email()
  File "C:/ALEVEL/PYONLINE2/lesson4/lesson4_practice_review.py", line 24, in validate_email
    raise EmailIsAlreadyTakenException()
EmailIsAlreadyTakenException
